#!/bin/bash
echo "DBT_TEST_USER_1=dbt_test_role_1" >> $GITHUB_ENV
echo "DBT_TEST_USER_2=dbt_test_role_2" >> $GITHUB_ENV
echo "DBT_TEST_USER_3=dbt_test_role_3" >> $GITHUB_ENV

TEST_ACCOUNT=${{ SNOWFLAKE_TEST_ACCOUNT }}
TEST_PASSWORD=${{ SNOWFLAKE_TEST_PASSWORD }}
TEST_USER=${{ SNOWFLAKE_TEST_USER }}
TEST_WAREHOUSE=${{ SNOWFLAKE_TEST_WAREHOUSE }}
TEST_OAUTH_REFRESH_TOKEN=${{ SNOWFLAKE_TEST_OAUTH_REFRESH_TOKEN }}
TEST_OAUTH_CLIENT_ID=${{ SNOWFLAKE_TEST_OAUTH_CLIENT_ID }}
TEST_OAUTH_CLIENT_SECRET=${{ SNOWFLAKE_TEST_OAUTH_CLIENT_SECRET }}
TEST_ALT_DATABASE=${{ SNOWFLAKE_TEST_ALT_DATABASE }}
TEST_ALT_WAREHOUSE=${{ SNOWFLAKE_TEST_ALT_WAREHOUSE }}
TEST_DATABASE=${{ SNOWFLAKE_TEST_DATABASE }}
TEST_QUOTED_DATABASE=${{ SNOWFLAKE_TEST_QUOTED_DATABASE }}
TEST_ROLE=${{ SNOWFLAKE_TEST_ROLE }}

JSON=\''{"SNOWFLAKE_TEST_ACCOUNT": "'"$TEST_ACCOUNT"'", "SNOWFLAKE_TEST_PASSWORD": "'"$TEST_PASSWORD"'", "SNOWFLAKE_TEST_USER": "'"$TEST_USER"'", "SNOWFLAKE_TEST_WAREHOUSE": "'"$TEST_WAREHOUSE"'", "SNOWFLAKE_TEST_OAUTH_REFRESH_TOKEN": "'"$TEST_OAUTH_REFRESH_TOKEN"'","SNOWFLAKE_TEST_OAUTH_CLIENT_ID":"'"$TEST_OAUTH_CLIENT_ID"'", "SNOWFLAKE_TEST_OAUTH_CLIENT_SECRET": "'"$TEST_OAUTH_CLIENT_SECRET"'", "SNOWFLAKE_TEST_ALT_DATABASE": "'"$TEST_ALT_DATABASE"'", "SNOWFLAKE_TEST_ALT_WAREHOUSE": "'"$TEST_ALT_WAREHOUSE"'", "SNOWFLAKE_TEST_DATABASE": "'"$TEST_DATABASE"'", "SNOWFLAKE_TEST_QUOTED_DATABASE": "'"$TEST_QUOTED_DATABASE"'", "SNOWFLAKE_TEST_ROLE": "'"$TEST_ROLE"'"}'\'

echo "JSON=$JSON" >> >> $GITHUB_ENV
